version: '3'

services:
    postgres:
        image: postgres:16.0
        environment:
            POSTGRES_DB: product_master
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"

volumes:
    pgdata:
